<?xml version="1.0" encoding="utf-8"?><workItemType dslVersion="1.1.0.0" Name="Sprint Backlog Item" source="C:\TFSWorkspaces\VS2008\SRM\Branches\DEVELOPMENT\ProcessTemplate\CustomWorkItems\SBI\Sprint Backlog Item.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner" />